### ISSUE TITLE
Legit from like 6 months ago + Stop Skidding

### ISSUE THREAD

**Issue by GDBOI101** [endermandev/AGS#1]
Just for the record, the Server is the Sulfur build that one of his devs leaked that he shared with me and told me to get working bc he couldn't do it himself.

**Comment by endermandev** [comment]
nah

**Comment by GDBOI101** [comment]
![image](https://user-images.githubusercontent.com/61432333/184548767-84bd37e8-b8ff-451d-914f-2429852586d0.png)

**Comment by GDBOI101** [comment]
https://cdn.discordapp.com/attachments/1004457712408600581/1008433705762697396/Skid.mp4

**Comment by GDBOI101** [comment]
https://user-images.githubusercontent.com/61432333/184549015-a9f0969e-fe34-4973-ad33-e425dbd1b33b.mp4
